### DISCUSSION TITLE
Unable to make connections between two LANs.

### DISCUSSION THREAD

**Discussion by srad0** [eProsima/DDS-Router#350] [Q&A]
My application is very much like the HelloWorld example, all UDP traffic, and built upon Fast-DDS 2.8.0. In trying to connect two LANs separated by a VPN using the DDS-Router 1.1.0 image (no NAT involved). If I start the DDS-Router container using --net=host in the Docker CLI, and I have the following interfaces on nodeA ...

```
    br-2cdcb5ab1cf: ...
    docker0: ...
    eno0: ...
    lo: ... 
    mpbr0: ...
    tun0: 172.10.12.101 ...
    virbro: ...

```
NodeB has same with tun0 as:
`    tun0: 172.12.20.20 ...`

I'm running a participant using defaults with the following config in each LAN with a different profile name ...

```
        <participant profile_name="node_a">
            <rtps>
                <builtin>
                    <discovery_config>
                        <discoveryProtocol>SIMPLE</discoveryProtocol>
                    </discovery_config>
                </builtin>
            </rtps>
        </participant>
```

For the router, I listen on the local VPN interface as the public facing IP and connect to the endpoint VPN interface.

```
participants:
  - name: lanA
    kind: local
    domain: 0

  - name: myWAN
    kind: wan
    domain: 0
    listening-addresses:
      - ip: 172.10.12.101
        port: 40777
    connection-addresses:
      - ip: 172.12.20.20
        port: 40666
```

For NodeB, listening and connection is swapped and local lan is named `wanB`.

Yet, I've not been successful in getting anything to connect or see messages of any sort. I'm wondering if there's something going on with the internal IP of the router and how my transports are set up by using default. Can anyone explain what's going on?

Is it possible IPv6 is what I should be using since I don't have NAT? I did try with IPv6 addresses, but that didn't work either. Also don't want to use a discovery server.

**Comment by jparisu** [comment]
Hi @srad0 

Your configuration seems correct. 
There are 2 possible issues here:
1. The DDS Routers are not discovering each other
2. The Endpoints are not discovering the DDS Router in their respective LANs.

Both can be due to the VPN capabilities. Check that your VPN allow multicast traffic in local, and check if you need to open some ports somehow to connect different LANs of the VPN. There are many other possibilities regarding the VPN: connection failures, firewalls, etc.

My suggestion is to use the Echo Participant. Check this example https://eprosima-dds-router.readthedocs.io/en/latest/rst/examples/echo_example.html .
Using this Participant you would be able to know if your DDS Routers discover each other and if they discover the endpoints in their LANs.

> For NodeB, listening and connection is swapped and local lan is named wanB.

**NOTE** If you are under a VPN, you just need one of the DDS Routers to have a listening-addresses and the other connection-addresses.
Check also the Domain ID of the other DDS Router, to be the same as the endpoints in its LAN.

**Comment by srad0** [comment]
I'm now testing on two hosts on my local subnet in order to simplify things in case the VPN is interfering and have changed the domain id's to be unique on each host. I'm still not seeing any messages at all with the echo participant added. I've confirmed firewalls are down.

If I stop the dds-routers and change the domain id's to be the same, that tells me my participants are working from host-to-host. Here's my latest router and profile config.

```
participants:

  - name: lanA
    kind: local
    domain: 1

  - name: myWAN
    kind: wan
    domain: 1
    listening-addresses:
      - ip: 192.168.20.31
        port: 40777
    connection-addresses:
      - ip: 192.168.20.33
        port: 40666

  - name: echo_participant
    kind: echo
    discovery: true
    data: true
    verbose: true

```    

```
participants:

  - name: lanB
    kind: local
    domain: 2

  - name: myWAN
    kind: wan
    domain: 2
    listening-addresses:
      - ip: 192.168.20.33
        port: 40666
    connection-addresses:
      - ip: 192.168.20.31
        port: 40777

  - name: echo_participant
    kind: echo
    discovery: true
    data: true
    verbose: true

```
Profile for nodeA.
```
        <participant profile_name="nodeA">
            <domainId>1</domainId>
            <rtps>
                <builtin>
                    <discovery_config>
                        <discoveryProtocol>SIMPLE</discoveryProtocol>
                    </discovery_config>
                </builtin>
            </rtps>
        </participant>

```
Profile for nodeB.
```
        <participant profile_name="nodeB">
            <domainId>2</domainId>
            <rtps>
                <builtin>
                    <discovery_config>
                        <discoveryProtocol>SIMPLE</discoveryProtocol>
                    </discovery_config>
                </builtin>
            </rtps>
        </participant>

```
Also, after staring routerA in lanA, should the router's echo participant print messages upon starting the local participant without even connecting to routerB? I'm just not seeing any messages at all. However, and I know this is wrong, but if I change both participants to the same domain and start a router, they of course talk and I see messages of "new endpoint discovered" in the router output.
