### DISCUSSION TITLE
Public IP for DDS routers behind DNAT

### DISCUSSION THREAD

**Discussion by PierreNeumann** [eProsima/DDS-Router#363] [Q&A] [answered]
Hi, 

I successfully run my setup over the Internet. 
My wan server is behind a proxy which redirect the port 11666 to the dds-router. 

Everything work fine if I specify my proxy public IP address in the DDS router configuration. 

I would like to use a more generic configuration like this : 

```
  - name: WanParticipant                                          
    kind: wan                                               
    listening-addresses:
      - ip: 0.0.0.0                                           
        port: 11666                                            
        transport: tcp
```

But that's not working. 
Is it possible to achieve a kind of configuration that avoid me to know my public IP address ?
