### DISCUSSION TITLE
DDS Router with ROS and flaky discovery

### DISCUSSION THREAD

**Discussion by johnny555** [eProsima/DDS-Router#392] [Q&A]
Thanks for a great tool. 

I'm using it to route data on a local LAN, but from inside a docker container on a Windows 11 host. I have to do this because Windows 11 doesn't support routing UDP into their virtual machines/docker containers. I'm building a ROS system, the robot is on the lan running Linux, but the human control (RVIZ) is inside the docker running windows. The problem I get is that ros2 topic list doesn't show all of the topics, and sometimes ros2 topic echo doesn't work. 

I'm abit stuck trying to debug this. Any tips on how to debug it, or perhaps something I missed in the configuration would be helpful! Thanks! 

dds-router config for docker running on Windows 11: 

```
version: v3.0 # 0

# PARTICIPANTS
participants:
  - name: DDS_LAN_B
    kind: local
    domain: 0

  - name: WANClient # 6
    kind: wan-discovery-server # 7
    discovery-server-guid:
      id: 2 # 8
    connection-addresses: # 9
      - discovery-server-guid:
          id: 1 # 10
        addresses: # 11
          - ip: 192.168.1.122
            port: 11888
            transport: tcp

  - name: ServerROS2 # 5
    kind: local-discovery-server # 6
    discovery-server-guid:
      ros-discovery-server: true # 7
      id: 3 # 8
    listening-addresses: # 9
      - domain: localhost # 10
        port: 11311 # 11

  - name: EchoParticipant # 6
    kind: echo # 7
    discovery: true # 8
    data: false # 9
    verbose: false # 10

```

And config running on the robot: 

```
version: v3.0 

participants:
  

  - name: DDS_LAN_A
    kind: local
    domain: 0

 
  - name: WANServerKrytn                                               
    kind: wan-discovery-server                                    
    discovery-server-guid:
      id: 1                                                       
    listening-addresses:                                
      - ip: 192.168.1.122                                
        port: 11888                                         
        transport: tcp            
```

If I go `ros2 topic list` on the robot I get:

```
/bond
/camera/color/camera_info
/camera/color/image_raw
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_rect_raw
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/extrinsics/depth_to_depth
/camera/imu
/cmd_vel
/controller_server/transition_event
/cost_cloud
/diff_drive_base_controller/cmd_vel_unstamped
/dynamic_joint_states
/evaluation
/global_costmap/costmap_raw
/global_costmap/published_footprint
/joint_state_broadcaster/transition_event
/joint_states
/joy
/joy/set_feedback
/local_costmap/clearing_endpoints
/local_costmap/costmap
/local_costmap/costmap_raw
/local_costmap/costmap_updates
/local_costmap/local_costmap/transition_event
/local_costmap/published_footprint
/local_costmap/voxel_grid
/local_plan
/map
/map_metadata
/marker
/parameter_events
/plan_smoothed
/pose
/received_global_plan
/robot_description
/rosout
/scan
/slam_toolbox/feedback
/slam_toolbox/graph_visualization
/slam_toolbox/scan_visualization
/slam_toolbox/update
/smoother_server/transition_event
/tf
/tf_static
/transformed_global_plan
/velocity_smoother/transition_event
```

but if I do the same in the Windows11 docker I get alot fewer results: 

```
/camera/color/image_raw
/diff_drive_base_controller/cmd_vel_unstamped
/joint_states
/joy
/joy/set_feedback
/parameter_events
/rosout
```
