### DISCUSSION TITLE
DDS-Router doesn't work once setting ROS_LOCALHOST_ONLY in Humble

### DISCUSSION THREAD

**Discussion by Barry-Xu-2018** [eProsima/DDS-Router#488] [Q&A] [answered]
I found DDS-Router doesn't work once setting ROS_LOCALHOST_ONLY in Humble. 

Test environment:
On terminal 1, run talker:
```
# source /opt/ros/humble/setup.bash
# export ROS_LOCALHOST_ONLY=1
# ROS_DOMAIN_ID=0 ros2 run demo_nodes_cpp talker
```

On terminal 2, run listener:
```
# source /opt/ros/humble/setup.bash
# export ROS_LOCALHOST_ONLY=1
# ROS_DOMAIN_ID=1 ros2 run demo_nodes_cpp listener
```

On terminal 3, run dds-router:
```
# cat ros2_router/route_local.yaml
##################################
# CONFIGURATION VERSION
version: v4.0


##################################
# PARTICIPANTS
participants:

  - name: ROS_2_Domain_0
    kind: local
    domain: 0

  - name: ROS_2_Domain_1
    kind: local
    domain: 1

# ddsrouter --config-path /root/ros2_router/route_local.yaml 
```

If I unset ROS_LOCALHOST_ONLY in terminal 1 and terminal 2, listener can receive messages from talker.   

In ros2, if ROS_LOCALHOST_ONLY is enable, it will do  
https://github.com/ros2/rmw_fastrtps/blob/37f7ef88fbec216d47883763f185bd39fc50b5a1/rmw_fastrtps_shared_cpp/src/participant.cpp#L165-L177  

```c++
  if (localhost_only) {
    // In order to use the interface white list, we need to disable the default transport config
    domainParticipantQos.transport().use_builtin_transports = false;


    // Add a UDPv4 transport with only localhost enabled
    auto udp_transport = std::make_shared<eprosima::fastdds::rtps::UDPv4TransportDescriptor>();
    udp_transport->interfaceWhiteList.emplace_back("127.0.0.1");
    domainParticipantQos.transport().user_transports.push_back(udp_transport);


    // Add SHM transport if available
    auto shm_transport = std::make_shared<eprosima::fastdds::rtps::SharedMemTransportDescriptor>();
    domainParticipantQos.transport().user_transports.push_back(shm_transport);
  }
```

About transport, does the DDS-Router have any special configuration for this case ?

**Comment by juanlofer-eprosima** [comment]
Hi @Barry-Xu-2018 , which version of DDS-Router are you using? And against which Fast-DDS version did you build? Are the three processes run in the same Docker container?

**Comment by Barry-Xu-2018** [comment]
@juanlofer-eprosima 

DDS-Router is v2.1.0 and Fast-DDS is v2.13.1.

> Are the three processes run in the same Docker container?

Yes.

**Comment by juanlofer-eprosima** [comment, marked as answer]
Hi @Barry-Xu-2018 , this is a known problem affecting older Fast-DDS versions (including v2.6 present in Humble). The explanation and fix was introduced [here](https://github.com/eProsima/Fast-DDS/pull/3733). If willing to enforce localhost communication in this case you would need to also add a whitelist to your local router participants, as shown [here](https://eprosima-dds-router.readthedocs.io/en/v2.2.0/rst/user_manual/configuration.html#interface-whitelist), i.e.:

```
# CONFIGURATION VERSION
version: v4.0


##################################
# PARTICIPANTS
participants:

  - name: ROS_2_Domain_0
    kind: local
    domain: 0
    whitelist-interfaces:
      - "127.0.0.1"

  - name: ROS_2_Domain_1
    kind: local
    domain: 1
    whitelist-interfaces:
      - "127.0.0.1"
```
