### ISSUE TITLE
DDS Router invalid when the network is bad(or disconnected)

### ISSUE THREAD

**Issue by luzw5** [eProsima/DDS-Router#397]
Hello, I am using DDSRouter recently, but I encountered a problem. I configured dds router on both my server and client, but when the network condition is very bad（or disconnected）, sometimes ddsrouter will stop routing valid data. At this time, restart dds router on the client side, and the data can be transmitted again. I would like to ask what is the reason for this problem?

**Comment by juanlofer-eprosima** [comment]
Hi @luzw5 

We will need to know more details to help you. What do you mean by "stop routing **valid** data"? What are the YAML configurations you are using? Is this connection through WAN or in a LAN?

Best regards

**Comment by luzw5** [comment]
Thank you for your reply, I will provide you with more information.  
![test](https://github.com/eProsima/DDS-Router/assets/102200262/fdfddf67-b003-42de-ab4f-f1c9ff13c044)


Robot1 
```
builtin-topics:
  - name: robot_state
    type: FreeFleetData::RobotState

  - name: task_result
    type: TaskResult::ResultData

  - name: mode_request
    type: FreeFleetData::ModeRequest

  - name: path_request
    type: FreeFleetData::PathRequest

  - name: destination_request
    type: FreeFleetData::DestinationRequest

  - name: photo_task_request
    type: PhotoTask::PhotoTaskRequest

  - name: task_request
    type: TaskRequest::RequestData



version: v3.0                                                    
participants:

  - name: SimpleParticipant                                       
    kind: local                                                  
    domain: 44                                                  

  - name: echo_participantD1 
    kind: echo
    data: true             
    verbose: true    
    discovery: true  

  - name: WanParticipantD1                                   
    kind: wan                                               
    connection-addresses:                                   
      - domain: server
        port: 9010
        transport: tcp
```
Robot 2

```
builtin-topics:
  - name: robot_state
    type: FreeFleetData::RobotState

  - name: task_result
    type: TaskResult::ResultData

  - name: mode_request
    type: FreeFleetData::ModeRequest

  - name: path_request
    type: FreeFleetData::PathRequest

  - name: destination_request
    type: FreeFleetData::DestinationRequest

  - name: photo_task_request
    type: PhotoTask::PhotoTaskRequest

  - name: task_request
    type: TaskRequest::RequestData



version: v3.0                                                    
participants:

  - name: SimpleParticipant                                       
    kind: local                                                  
    domain: 42                                                  

  - name: echo_participantD1 
    kind: echo
    data: true             
    verbose: true    
    discovery: true  

  - name: WanParticipantD1                                   
    kind: wan                                               
    connection-addresses:                                   
      - domain: server
        port: 9017
        transport: tcp
```

Server
```
version: v3.0                                                    
builtin-topics:
  - name: robot_state
    type: FreeFleetData::RobotState

  - name: task_result
    type: TaskResult::ResultData

  - name: mode_request
    type: FreeFleetData::ModeRequest

  - name: path_request
    type: FreeFleetData::PathRequest

  - name: destination_request
    type: FreeFleetData::DestinationRequest

  - name: photo_task_request
    type: PhotoTask::PhotoTaskRequest

  - name: task_request
    type: TaskRequest::RequestData

participants:

  - name: ParticipantServer                                     
    kind: local                                                  
    domain: 4                                                   

  - name: EchoParticipantServer                                          
    kind: echo                                                       
    discovery: true                                                  
    data: true                                                       
    verbose: true                                                    

  - name: WanParticipantServerD1                                          
    kind: wan                                                  
    listening-addresses:
      - ip: 10.164.24.239                                           
        port: 9010                                              
        transport: tcp                                        

  - name: WanParticipantServerD2                            
    kind: wan                                            
    listening-addresses:
      - ip: 10.164.24.239                                       
        port: 9017                                          
        transport: tcp 
```
