### ISSUE TITLE
Not configuration file given, using default file DDS_ROUTER_CONFIGURATION.yaml

### ISSUE THREAD

**Issue by magladko** [eProsima/DDS-Router#404]
Hi,
I downloaded the docker image of DDS-Router, but I get this messages:

```
kornel@kornel-LG:~/Programs/dds_router_ws$ docker run -it --net=host -v /home/kornel/Programs/dds_router_ws/DDS_ROUTER_CONFIGURATION.yaml:/root/DDS_ROUTER_CONFIGURATION.yaml ubuntu-ddsrouter:v2.0.0
Not configuration file given, using default file DDS_ROUTER_CONFIGURATION.yaml.
Starting DDS Router Tool execution.
DDS Router running.
```

I am specifically worried about 'Not configuration file given, using default file DDS_ROUTER_CONFIGURATION.yaml.' that I get despite the fact of creating a mounted drive with it present.

Source of my yaml file I copied from here:
https://eprosima-dds-router.readthedocs.io/en/latest/rst/examples/echo_example.html#examples-echo-example

Which is:
```
################
# ECHO EXAMPLE #
################

##################################
# CONFIGURATION VERSION
version: v3.0                                                         # 0

##################################
# ALLOWED TOPICS
# Allowing FastDDS and ROS2 HelloWorld demo examples topics

allowlist:
  - name: HelloWorldTopic                                             # 1
    type: HelloWorld                                                  # 1
  - name: rt/chatter                                                  # 2
    type: std_msgs::msg::dds_::String_

##################################
# PARTICIPANTS
participants:

##################################
# SIMPLE PARTICIPANT
# This participant will subscribe to topics in allowlist in specific domain and listen every message published there

  - name: SimpleParticipant                                           # 3
    kind: local                                                       # 4
    domain: 0                                                         # 5

##################################
# ECHO PARTICIPANT
# This Participant will print in stdout every message received by the other Participants, as well as discovery information

  - name: EchoParticipant                                             # 6
    kind: echo                                                        # 7
    discovery: true                                                   # 8
    data: true                                                        # 9
    verbose: true                                                     # 10


##################################
# CONFIGURATION DESCRIPTION

# This configuration example configures a DDS Router to listen to every message published in domain 0 in topics
# HelloWorldTopic (from Fast DDS HelloWorld) and rt/chatter from ROS2 demo_nodes, and to print the received
# messages in stdout. Information regarding discovery events is also printed to stdout.

# 0: Use YAML configuration version v3.0

# 1: Allow DDS Topic Name <HelloWorldTopic> with type <HelloWorld>.

# 2: Insert new topics in order to route them.

# 3: New Participant with name <SimpleParticipant>.

# 4: Kind of SimpleParticipant: <local>.
# LAN UDP communication with default simple multicast discovery.

# 5: SimpleParticipant will use DDS Domain ID <0>.

# 6: New Participant with name <EchoParticipant>.

# 7: Kind of EchoParticipant: <echo>.

# 8: Print a trace to stdout every time an Endpoint is discovered.

# 9: Print a trace to stdout every time a new data message arrives to the router.

# 10: Display verbose information regarding received messages (receiver endpoint_guid and data payload).
```

Then when I run ros2 example nodes:
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ros2 run demo_nodes_cpp listener / talker

I don't get any logs regarding communication between them.
