### ISSUE TITLE
dsrouter v3.2.0 receives topics on robot and dev PC, but not in cloud (OCI) with identical config

### ISSUE THREAD

**Issue by bubssi528** [eProsima/DDS-Router#517]
Hi, thank you for maintaining eprosima ddsrouter.

I'm using ddsrouter v3.2.0 in three environments — robot (Jetson Nano), local dev PC, and cloud (OCI). While it works well on both the robot and the development PC, it fails to receive any topics in the cloud, even though the configuration files are nearly identical.

Below is a detailed breakdown of each environment and their respective configurations.

🤖 Robot (Jetson Nano, Unitree Go2)
ROS 2: Humble
Running inside a Docker container
Status: ✅ Working as expected
Sends data via WANClient1 (UDP) and WANClient2 (TCP)
Topics filtered via allowlist, including:
/rt/odom, /rt/tf*, /rt/joint_states, etc.

Configuration File (Robot)
``` yaml
participants:
  - name: WANClient1
    kind: wan
    connection-addresses:
      - ip: 172.30.1.76
        port: 5000
        transport: udp

  - name: WANClient2
    kind: wan
    connection-addresses:
      - domain: my.domain.com
        port: 5000
        transport: tcp

```

💻 Dev PC
OS: Ubuntu 22.04
ROS 2: Humble
Running natively (not in Docker)
Status: ✅ Works fine — I can echo all expected topics
Configuration:

``` yaml
specs:
  allowlist:
    - name: "*"
      type: "*"
participants:
  - name: SimpleParticipant
    kind: local
    domain: 0
  - name: echoParticipant
    kind: echo
    data: false
  - name: WANServer
    kind: wan
    listening-addresses:
      - ip: 0.0.0.0
        port: 5000
        transport: udp
```

☁️ Cloud (Oracle Cloud Infrastructure)
OS: Ubuntu 22.04
ROS 2: Humble
Running inside a Docker container
Public IP / domain is correctly set up
Ports (including 5000/tcp and udp) are open
Status: ❌ No topics received — even though DDSRouter starts with no errors
Configuration (only difference is transport: tcp):

``` yaml
specs:
  allowlist:
    - name: "*"
      type: "*"
participants:
  - name: SimpleParticipant
    kind: local
    domain: 0
  - name: echoParticipant
    kind: echo
    data: false
  - name: WANServer
    kind: wan
    listening-addresses:
      - ip: 0.0.0.0
        port: 5000
        transport: tcp
```

❓ Question
1. Is ddsrouter fully compatible with TCP transport in cloud environments like OCI?

2. Are there any known limitations or extra configuration steps required for TCP mode in cloud-hosted containers?

3. Could NAT or OCI VCN behavior be interfering with DDS discovery or topic relay over TCP?

4. Any insights or suggestions would be very helpful. Thank you in advance!
